#!/usr/bin/env python3
import json, os, argparse
from pathlib import Path

def generate_json_data_paired(reference_fasta_path, output_directory_name="output"):
    directory = Path(os.getcwd())
    fastq_files = list(directory.glob("*.fastq.gz"))

    # Temporary storage
    r1_files = {}
    r2_files = {}

    # Separate R1 and R2
    for f in fastq_files:
        fname = f.name
        if "R1" in fname:
            # use filename prefix as sample name (before _R1)
            sample = fname.split("R1")[0].rstrip("_")
            r1_files[sample] = str(f)
        elif "R2" in fname:
            sample = fname.split("R2")[0].rstrip("_")
            r2_files[sample] = str(f)

    # Combine into config data structure
    config_data = {}
    for sample in set(r1_files.keys()) | set(r2_files.keys()):
        config_data[sample] = {
        "mode": "paired-end-mode",
        "reference-fasta": reference_fasta_path,
        "output-directory": f"{sample}_{output_directory_name}",
        "paired-end-mode": {
            "R1": r1_files.get(sample),
            "R2": r2_files.get(sample)
        },
        "analysis-parameters": {
            "do-benchmarks": True,
            "do-alignment": True,
            "do-analysis": True,
            "do-alignment-stats": True,
            "do-alignment-visualization": True,
            "do-alignment-score-plot": True,
            "do-mpileup": True,
            "do-mpileup-fullanalysis": True,
            "do-mpileup-simpleanalysis": True,
            "do-mpileup-visualization": True,
            "do-association-analysis": True
        }
    }
    return config_data

def generate_json_data_merged(reference_fasta_path, output_directory_name="output"):
    directory = Path(os.getcwd())
    # Ideally these files would be generated by a merging step in the pipeline
    # For now, we will just look for files with "R1" as a proxy for merged / single readthrough files
    # merged_files = list(directory.glob("*merged.fastq.gz"))
    merged_files = list(directory.glob("*R1*.fastq.gz"))

    config_data = {}
    for f in merged_files:
        fname = f.name
        sample = fname.split("R1")[0].rstrip("_")
        config_data[sample] = {
            "mode": "merged-mode",
            "reference-fasta": reference_fasta_path,
            "output-directory": f"{sample}_{output_directory_name}",
            "merged-mode": {
                "R1": str(f)
            },
            "analysis-parameters": {
                "do-benchmarks": True,
                "do-alignment": True,
                "do-analysis": True,
                "do-alignment-stats": True,
                "do-alignment-visualization": True,
                "do-alignment-score-plot": True,
                "do-mpileup": True,
                "do-mpileup-fullanalysis": True,
                "do-mpileup-simpleanalysis": True,
                "do-mpileup-visualization": True,
                "do-association-analysis": True
            }
        }
    return config_data

def main():
    # Call on this script in a directory which only contains the fastq files you want a config for (these will share a reference fasta file and the output dir prefix)
    parser = argparse.ArgumentParser(description="Generate JSON config for NGS pipeline")
    parser.add_argument("--reference", default="reference.fasta", help="Path to reference FASTA file with respect to cwd or full path")
    parser.add_argument("--output", default="output", help="Output directory name")
    parser.add_argument("--mode", choices=["paired-end", "merged"], default="paired-end", help="Analysis mode - paired-end (aka. double-readthrough) or merged (aka. single-readthrough)")

    args = parser.parse_args()

    if args.mode == "paired-end":
        config_data = generate_json_data_paired(args.reference, args.output)
    else:
        config_data = generate_json_data_merged(args.reference, args.output)

    for sample, data in config_data.items():
        with open(f'generated_config_{sample}.json','w') as f:
            json.dump(data,f)

if __name__ == "__main__":
    main()